# 4. Linear Models {-}
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(rethinking)
```

## Code within the Chapter {-}

### 4.3.1 The Data {-}
```{r}
data("Howell1")
d <- Howell1
str(d)
```

```{r}
d$height
```

```{r}
d2 <- d[ d$age >= 18, ]
```

### 4.3.2 The model. {-}

```{r}
dens(d2$height)
```

```{r}
curve(dnorm(x, 178, 20), from=100, to=250)
```

```{r}
curve(dunif(x, 0, 50), from =-10, 60)
```

```{r}
sample_mu <- rnorm(1e5, 178, 20)
sample_sigma <- runif(1e5, 0, 50)
prior_h <- rnorm(1e5, sample_mu, sample_sigma)
dens(prior_h)
```
Reducing the `mu` from the book because it wasn't very fine grained.
```{r}
mu.list <- seq(from=150, to=160, length.out=200)
sigma.list <- seq(from=5, to=9, length.out=200)
post <- expand.grid(mu=mu.list, sigma=sigma.list)
post$LL <- sapply(1:nrow(post), function(i) sum(dnorm(
  d2$height, 
  mean=post$mu[i],
  sd=post$sigma[i],
  log=TRUE
)))
post$prod <- post$LL + dnorm(post$mu, 178, 20, TRUE) + dunif(post$sigma, 0, 50, TRUE)
post$prob <- exp(post$prod - max(post$prod))
```

```{r}
contour_xyz(post$mu, post$sigma, post$prob)
```
```{r}
image_xyz(post$mu, post$sigma, post$prob)
```
```{r}
sample.rows <- sample(1:nrow(post), size=1e4, replace=TRUE, prob=post$prob)
sample.mu <- post$mu[sample.rows]
sample.sigma <- post$sigma[sample.rows]
```

```{r}
plot(sample.mu, sample.sigma, cex=.5, pch=16, col=col.alpha(rangi2, 0.1))
```

```{r}
par(mfcol=c(1,2))
dens(sample.mu)
dens(sample.sigma)
```
```{r}
HPDI(sample.mu)
HPDI(sample.sigma)
```
#### Overthinking: Sample size and the normality of $\sigma$'s posterior {-}
```{r}
d3 <- sample(d2$height, size=20)
mu.list <- seq(from=150, to=160, length.out=200)
sigma.list <- seq(from=5, to=9, length.out=200)
post2 <- expand.grid(mu=mu.list, sigma=sigma.list)
post2$LL <- sapply(1:nrow(post), function(i) sum(dnorm(
  d3, 
  mean=post$mu[i],
  sd=post$sigma[i],
  log=TRUE
)))
post2$prod <- post2$LL + dnorm(post2$mu, 178, 20, TRUE) + dunif(post2$sigma, 0, 50, TRUE)
post2$prob <- exp(post2$prod - max(post2$prod))
sample2.rows <- sample(1:nrow(post), size=1e4, replace=TRUE, prob=post2$prob)
sample2.mu <- post2$mu[sample2.rows]
sample2.sigma <- post2$sigma[sample2.rows]
plot(sample2.mu, sample2.sigma, cex=0.5, col=col.alpha(rangi2,0.1),
     xlab='mu', ylab='sigma', pch=16)
```

```{r}
dens(sample2.sigma, norm.comp=TRUE)
```

### 4.3.5 Fitting the model with `map` {-}